name: "목표 설정"
description: 목표 설정 Issue 작성 양식입니다.
labels: ["goal-setting"]
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "[Feat] 로그인 기능 추가"
  - type: textarea
    id: goal-description
    attributes:
      label: 목표
      description: 달성하고자 하는 목표를 구체적으로 적어주세요.
      placeholder: 여기에 목표를 작성해 주세요.
    validations:
      required: true
  - type: textarea
    id: detailed-tasks
    attributes:
      label: 세부 태스크
      description: 목표를 달성하기 위해 수행해야 할 세부 태스크를 나열해주세요.
      placeholder: 여기에 세부 태스크를 작성해 주세요.
    validations:
      required: false
